2020-07-16 23:08:11,820 ERROR: Exception on /login [GET] [in /Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/skedzie/Development/learn/python/microblog/app/routes.py", line 57, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/skedzie/Development/learn/python/microblog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/skedzie/Development/learn/python/microblog/app/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/skedzie/Development/learn/python/microblog/app/templates/login.html", line 27, in block "content"
    <a href="{{ url_for('reset_password') }}">Click to Reset It</a>
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password'. Did you mean 'reset_password_request' instead?
2020-07-16 23:08:13,784 ERROR: Exception on /login [GET] [in /Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/skedzie/Development/learn/python/microblog/app/routes.py", line 57, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/skedzie/Development/learn/python/microblog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/skedzie/Development/learn/python/microblog/app/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/skedzie/Development/learn/python/microblog/app/templates/login.html", line 27, in block "content"
    <a href="{{ url_for('reset_password') }}">Click to Reset It</a>
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password'. Did you mean 'reset_password_request' instead?
2020-07-16 23:09:16,856 INFO: Microblog startup [in /Users/skedzie/Development/learn/python/microblog/app/__init__.py:46]
2020-07-16 23:10:57,710 ERROR: Exception on /reset-password [POST] [in /Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/skedzie/Development/learn/python/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/skedzie/Development/learn/python/microblog/app/routes.py", line 174, in reset_password
    send_mail(user)
TypeError: send_mail() missing 4 required positional arguments: 'sender', 'recipients', 'text_body', and 'html_body'
2020-07-16 23:33:46,317 INFO: Microblog startup [in /Users/skedzie/Development/learn/python/microblog/app/__init__.py:46]
